import os
import urllib.parse

def generate_index(root_dir):
    """
    Generates an HTML index file listing all files and directories recursively.
    """
    
    html_content = """<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Study Base Index</title>
    <style>
        body { font-family: sans-serif; max-width: 900px; margin: 2rem auto; padding: 0 1rem; line-height: 1.6; }
        h1 { border-bottom: 2px solid #eee; padding-bottom: 0.5rem; }
        ul { list-style-type: none; padding-left: 20px; }
        li { margin: 0.2rem 0; }
        a { color: #0070f3; text-decoration: none; }
        a:hover { text-decoration: underline; }
        .dir { font-weight: bold; margin-top: 10px; color: #333; }
        .file { color: #555; }
    </style>
</head>
<body>
    <h1>Study Base File Index</h1>
    <p>This index is automatically generated.</p>
    <ul>
"""

    for root, dirs, files in os.walk(root_dir):
        # Exclude hidden directories and .git
        dirs[:] = [d for d in dirs if not d.startswith('.') and d != 'node_modules']
        files = [f for f in files if not f.startswith('.') and f != 'index.html' and f != 'generate_index.py']

        # Sort for consistent order
        dirs.sort()
        files.sort()

        # Calculate relative path from root_dir
        rel_path = os.path.relpath(root, root_dir)
        if rel_path == '.':
            rel_path = ''
        
        # Don't show root listing as a separate header, just list its files
        if rel_path:
             html_content += f'<li class="dir">📁 {rel_path}</li><ul>'

        for f in files:
            file_path = os.path.join(rel_path, f) if rel_path else f
            # Encode path for URL
            url_path = urllib.parse.quote(file_path.replace(os.sep, '/'))
            html_content += f'<li class="file">📄 <a href="{url_path}">{f}</a></li>'
            
        if rel_path:
            html_content += "</ul>"

    html_content += """
    </ul>
    <div style="margin-top: 50px; font-size: 0.8em; color: #999;">
        Generated by generate_index.py
    </div>
</body>
</html>
"""

    with open(os.path.join(root_dir, 'index.html'), 'w', encoding='utf-8') as f:
        f.write(html_content)
    print("index.html generated successfully.")

if __name__ == "__main__":
    generate_index('.')
